name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build Gradle
        run: ./gradlew clean build

      - name: Create deploy directory
        run: mkdir -p deploy

      - name: Copy appsepc.yml to deploy
        run: cp appspec.yml deploy/

      - name: Copy sh files to deploy
        run: cp *.sh deploy/

      - name: Copy jar files to deploy
        run: cp build/libs/*.jar deploy/

      - name: Compress deploy directory
        run: zip -r beat-music deploy/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-northeast-2

      - name: List Files
        run: ls -al

      - name: Copy zip file to AWS S3 bucket
        run: aws s3 cp beat-music.zip s3://beat-music-s3

      - name: Deploy to AWS EC2 from S3
        run: |
          aws deploy create-deployment \
              --application-name beat-music-code-deploy-app \
              --deployment-config-name CodeDeployDefault.AllAtOnce \
              --deployment-group-name beat-music-code-deploy-app-group \
              --s3-location bucket=beat-music-s3,bundleType=zip,key=beat-music.zip