spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  profiles:
    group:
      real: real

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace


CLIENT_URL: ""

